# Generated by Django 6.0.1 on 2026-01-26 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="휴대전화 번호",
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="전화번호는 010-XXXX-XXXX 형식이어야 합니다.",
                        regex="^010-\\d{4}-\\d{4}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="이메일 주소", max_length=254, unique=True
            ),
        ),
    ]
