# Generated by Django 6.0.1 on 2026-01-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location_id',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, db_column='location_id', help_text='기본 활동 지역', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_location', to='locations.location', verbose_name='주소'),
        ),
    ]
