# Generated by Django 6.0.1 on 2026-01-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='댓글 내용')),
                ('is_author', models.BooleanField(blank=True, null=True, verbose_name='주최자 댓글 여부')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'Comment',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='해시태그명')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
            ],
            options={
                'verbose_name': '해시태그',
                'verbose_name_plural': '해시태그',
                'db_table': 'Hashtag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('APPROVED', '승인됨'), ('REJECTED', '거절됨'), ('CANCELLED', '취소'), ('COMPLETED', '완료')], default='PENDING', max_length=20, verbose_name='참여 상태')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='신청 시간')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='상태 변경 시간')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='승인 시간')),
            ],
            options={
                'verbose_name': '참여 상태',
                'verbose_name_plural': '참여 상태',
                'db_table': 'Participation',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('moim_date', models.DateField(blank=True, null=True, verbose_name='모임 날짜')),
                ('moim_time', models.TimeField(blank=True, null=True, verbose_name='모임 시간')),
                ('max_people', models.IntegerField(blank=True, null=True, verbose_name='최대 인원')),
                ('is_closed', models.BooleanField(blank=True, default=False, null=True, verbose_name='마감 여부')),
                ('is_cancelled', models.BooleanField(blank=True, default=False, null=True, verbose_name='폭파 여부')),
                ('save', models.BooleanField(blank=True, default=False, null=True, verbose_name='임시저장 여부')),
                ('gender_restriction', models.IntegerField(blank=True, choices=[(0, '누구나'), (1, '남성만'), (2, '여성만')], default=0, null=True, verbose_name='성별 제한')),
                ('age_restriction', models.IntegerField(blank=True, default=0, null=True, verbose_name='나이 제한')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'db_table': 'Post',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '게시글-해시태그',
                'verbose_name_plural': '게시글-해시태그',
                'db_table': 'PostHashtag',
            },
        ),
    ]
