# Generated by Django 6.0.1 on 2026-01-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('moong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location_id',
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='모임 장소'),
        ),
    ]
