# Generated by Django 6.0.1 on 2026-01-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moong', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='save',
            new_name='complete',
        ),
    ]
