# Generated by Django 6.0.1 on 2026-01-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sido", models.CharField(max_length=20)),
                ("sigungu", models.CharField(max_length=20)),
                ("eupmyeondong", models.CharField(max_length=20)),
            ],
        ),
    ]
